name: Deal Hunter
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 mins
  workflow_dispatch: # Allows manual button click

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests feedparser
      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          EARNKARO_TOKEN: ${{ secrets.EARNKARO_TOKEN }}
